name: clang-scan

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ci-clang-scan
    if: ${{ github.repository != 'opcm/pcm' }}    

    steps:
    - uses: actions/checkout@v2
    - name: Preparation
      run: |
        cd ${{ github.workspace }}/src
        git clone https://github.com/simdjson/simdjson.git
        cd ..
    - name: Configure CMake
      run: |
        cmake --version
        rm -rf ${{ github.workspace }}/build
        scan-build cmake -B ${{ github.workspace }}/build
    - name: Scan build
      run: |
        cd ${{ github.workspace }}/build
        scan-build --exclude simdjson --status-bugs make -j
