name: kw-linux

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ci-kw-linux
    if: ${{ github.repository != 'opcm/pcm' }}

    steps:
    - uses: actions/checkout@v2
    - name: kw
      run: |
        cd src
        git clone https://github.com/simdjson/simdjson.git
        cd ..
        mkdir build
        cd build
        cmake ..
        ci-kw-linux.sh "echo No Preparation" "make -j"
